version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - HEALTHCHECK_DEBUG=true  # Enable debug mode
    container_name: codex
    image: codex
    healthcheck:
      test: [ "CMD", "python", "/app/healthcheck.py" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - Location/on/your/device/to/attach:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
