services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: codex
    image: codex
    volumes:
      - .:/app
      - /home/eosofficial/discord-bots/bot_logs/codex:/app/logs  # Persistent logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M